CREATE TABLE [dbo].[Hierarchies]
(
[Id] [bigint] NOT NULL IDENTITY(1, 1),
[Guid] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Hierarchies_Guid] DEFAULT (newid()),
[EntityTypeGuid] [uniqueidentifier] NOT NULL,
[Title] [nvarchar] (100) NOT NULL,
[Code] [nvarchar] (100) NULL,
[IconGuid] [uniqueidentifier] NULL,
[IconSvg] [nvarchar] (max) NULL,
[ParentId] [bigint] NULL,
[Description] [nvarchar] (max) NULL,
[Order] [int] NOT NULL,
[Show] [bit] NOT NULL,
[ItemsCount] [int] NULL,
[UrlKey] [nvarchar] (400) NULL,
[Level] [int] NULL,
[IsLeaf] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Hierarchies] ADD CONSTRAINT [PK_Hierarchies] PRIMARY KEY CLUSTERED  ([Id]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Hierarchies] ADD CONSTRAINT [IX_Hierarchies_Unique_ParentId_And_Title] UNIQUE NONCLUSTERED  ([ParentId], [Title]) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Hierarchies_Unique_UrlKey] ON [dbo].[Hierarchies] ([UrlKey]) WHERE ([UrlKey] IS NOT NULL) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Hierarchies] ADD CONSTRAINT [FK_Hierarchies_ParentId_Hierarchies_Id] FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Hierarchies] ([Id])
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
SET ANSI_PADDING ON
GO
SET ANSI_WARNINGS ON
GO
SET ARITHABORT ON
GO
SET CONCAT_NULL_YIELDS_NULL ON
GO
SET NUMERIC_ROUNDABORT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
